### ISSUE TITLE
Store client settings in local storage

### ISSUE THREAD

**Issue by mrozbarry** [mobtimeapp/mobtime#160]
## Tasks

 - [x] Store client sound preference in local storage
 - [x] On load, use an effect to check if the user has enabled sounds
   - [x] If yes, show a button at the top of the mobtime container (above the timer) for the user to click. This is necessary because the user has to interact with the web page at least once before sounds will play.
   - [x] If no, do nothing

## Bonus

 - Make it look pretty (if you're not sure, post a screenshot on your PR and I'll help)
